export * from './advantages'
export * from './contacts'
export * from './detailsServices'
export * from './galeryData'
export * from './navigationLinks'
export * from './pathData'
export * from './servicesTitles'