import { Footer, Header } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

const raleWay = Raleway ({
  subsets: ['cyrillic', 'latin'],
  display: 'swap'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={raleWay.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
